name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Update dependecies
      run: sudo apt install php-intl php-mbstring php-xml

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install

    - name: Run test suite
      run: vendor/bin/phpunit
